AWSTemplateFormatVersion: '2010-09-09'
Description: 'Sunray Feedback Labeling System - Amazon Bedrock Nova'

Parameters:
  Environment:
    Type: String
    Description: Environment for deployment
    AllowedValues:
      - dev
      - tst
      - qa
      - prd
    Default: dev
    ConstraintDescription: Must be dev, tst, qa, or prd
    
  NovaModelId:
    Type: String
    Description: |
      Amazon Nova model selection (via EU inference profile):
      
      Micro - Fastest, cheapest (~$0.035/1M tokens)
        Best for: Simple classification, high volume, POC/testing
        Cost: $1-3 per 10K feedbacks
      
      Lite - Balanced performance (~$0.06/1M tokens)
        Best for: Most production use cases
        Cost: $2-5 per 10K feedbacks
      
      2-Lite - Improved Lite version (newer)
        Best for: Latest features, similar cost to Lite
        Cost: $2-5 per 10K feedbacks
      
      Pro - Most capable (~$0.80/1M tokens)
        Best for: Complex reasoning, nuanced analysis
        Cost: $20-50 per 10K feedbacks
    Default: eu.amazon.nova-micro-v1:0
    AllowedValues:
      - eu.amazon.nova-micro-v1:0
      - eu.amazon.nova-lite-v1:0
      - eu.amazon.nova-2-lite-v1:0
      - eu.amazon.nova-pro-v1:0
    ConstraintDescription: Must be a valid Amazon Nova inference profile ID
    
Resources:
  # S3 Bucket for feedback storage
  FeedbackBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'sunray-feedback-nova-${Environment}-${AWS::Region}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Solution
          Value: sunray-feedback-labeling
        - Key: AIProvider
          Value: bedrock-nova

  # IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'sunray-feedback-nova-${Environment}-lambda-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub '${FeedbackBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !GetAtt FeedbackBucket.Arn
        - PolicyName: BedrockAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource: 
                  # Foundation models
                  - !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/*'
                  - !Sub 'arn:aws:bedrock:*::foundation-model/*'
                  # Inference profiles (REQUIRED for Nova)
                  - !Sub 'arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:inference-profile/*'
                  - !Sub 'arn:aws:bedrock:*:${AWS::AccountId}:inference-profile/*'

  # CloudWatch Log Group for Lambda
  FunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/sunray-feedback-nova-${Environment}-labeling-function'
      RetentionInDays: 7

  # The main Lambda function
  FeedbackLabelingFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'sunray-feedback-nova-${Environment}-labeling-function'
      Runtime: python3.11
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 300
      MemorySize: 512
      Environment:
        Variables:
          BEDROCK_MODEL_ID: !Ref NovaModelId
          OUTPUT_BUCKET: !Ref FeedbackBucket
          ENVIRONMENT: !Ref Environment
          # Optional override - set via Lambda console to test different models
          # MODEL_OVERRIDE: eu.amazon.nova-lite-v1:0
          # Available options:
          # eu.amazon.nova-micro-v1:0
          # eu.amazon.nova-lite-v1:0
          # eu.amazon.nova-2-lite-v1:0
          # eu.amazon.nova-pro-v1:0
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Solution
          Value: sunray-feedback-labeling
      Code:
        ZipFile: |
          import json
          import boto3
          import os
          from datetime import datetime
          from urllib.parse import unquote_plus
          
          s3 = boto3.client('s3')
          bedrock = boto3.client('bedrock-runtime')
          
          # Check for override first, then use default
          MODEL_ID = os.environ.get('MODEL_OVERRIDE', os.environ['BEDROCK_MODEL_ID'])
          OUTPUT_BUCKET = os.environ['OUTPUT_BUCKET']
          ENVIRONMENT = os.environ['ENVIRONMENT']
          
          print(f"Using model: {MODEL_ID}")
          if 'MODEL_OVERRIDE' in os.environ:
              print(f"⚠️  MODEL_OVERRIDE is set - using {MODEL_ID} instead of stack default")
          
          # Prompt template for Amazon Nova
          LABELING_PROMPT = """Analyze this customer feedback and label it accurately.

          Feedback: "{feedback_text}"
          
          You must return ONLY valid JSON (no markdown, no explanation) with these exact fields:
          - category: one of [product, service, delivery, payment, technical, general, positive_feedback]
          - sentiment: one of [positive, neutral, negative]
          - subcategory: specific issue type (e.g., "late_delivery", "poor_quality", "great_service")
          - language: detected language code (fi, en, et, lv, lt, or other)
          - priority: one of [low, medium, high]
          - summary: brief 1-sentence description in English
          - confidence: your confidence level (low, medium, high)
          
          Example output:
          {{"category":"delivery","sentiment":"negative","subcategory":"late_delivery","language":"en","priority":"high","summary":"Customer reports delayed package delivery","confidence":"high"}}
          
          Return only the JSON object, nothing else."""
          
          def invoke_nova(feedback_text):
              """Send feedback to Amazon Nova and get labeled response"""
              prompt = LABELING_PROMPT.format(feedback_text=feedback_text)
              
              # Amazon Nova uses the Converse API format
              request_body = {
                  "messages": [
                      {
                          "role": "user",
                          "content": [
                              {
                                  "text": prompt
                              }
                          ]
                      }
                  ],
                  "inferenceConfig": {
                      "max_new_tokens": 500,
                      "temperature": 0.3
                  }
              }
              
              response = bedrock.invoke_model(
                  modelId=MODEL_ID,
                  body=json.dumps(request_body)
              )
              
              response_body = json.loads(response['body'].read())
              
              # Extract text from Nova response
              nova_response = response_body['output']['message']['content'][0]['text']
              
              # Parse Nova's JSON response
              try:
                  labeled_data = json.loads(nova_response.strip())
                  return labeled_data
              except json.JSONDecodeError:
                  # Fallback if Nova doesn't return perfect JSON
                  return {
                      "error": "Failed to parse Nova response",
                      "raw_response": nova_response,
                      "category": "general",
                      "sentiment": "neutral",
                      "priority": "low"
                  }
          
          def lambda_handler(event, context):
              """Main handler - triggered by S3 upload"""
              print(f"Environment: {ENVIRONMENT}")
              print(f"Model: {MODEL_ID}")
              print(f"Received event: {json.dumps(event)}")
              
              results = []
              
              for record in event['Records']:
                  # Get the uploaded file details
                  bucket = record['s3']['bucket']['name']
                  key = unquote_plus(record['s3']['object']['key'])
                  
                  print(f"Processing: s3://{bucket}/{key}")
                  
                  try:
                      # Read the input file
                      response = s3.get_object(Bucket=bucket, Key=key)
                      file_content = response['Body'].read().decode('utf-8')
                      feedback_data = json.loads(file_content)
                      
                      # Handle both single feedback and arrays
                      feedbacks = feedback_data if isinstance(feedback_data, list) else [feedback_data]
                      
                      labeled_feedbacks = []
                      
                      for feedback in feedbacks:
                          feedback_text = feedback.get('feedback', feedback.get('message', feedback.get('text', '')))
                          
                          if not feedback_text:
                              print(f"No feedback text found in: {feedback}")
                              continue
                          
                          # Send to Nova for labeling
                          print(f"Labeling with Nova: {feedback_text[:100]}...")
                          labeled = invoke_nova(feedback_text)
                          
                          # Merge original data with labels
                          result = {
                              **feedback,
                              'labels': labeled,
                              'processed_at': datetime.utcnow().isoformat(),
                              'processor': 'amazon-nova',
                              'model': MODEL_ID,
                              'environment': ENVIRONMENT
                          }
                          
                          labeled_feedbacks.append(result)
                      
                      # Write to egress folder
                      timestamp = datetime.utcnow().strftime('%Y%m%d_%H%M%S')
                      original_filename = key.split('/')[-1].replace('.json', '')
                      output_key = f"egress/{original_filename}_labeled_{timestamp}.json"
                      
                      s3.put_object(
                          Bucket=OUTPUT_BUCKET,
                          Key=output_key,
                          Body=json.dumps(labeled_feedbacks, indent=2),
                          ContentType='application/json'
                      )
                      
                      print(f"✓ Labeled data written to: s3://{OUTPUT_BUCKET}/{output_key}")
                      
                      # Move original to archive
                      archive_key = key.replace('ingress/', 'archive/')
                      s3.copy_object(
                          Bucket=OUTPUT_BUCKET,
                          CopySource={'Bucket': bucket, 'Key': key},
                          Key=archive_key
                      )
                      s3.delete_object(Bucket=bucket, Key=key)
                      
                      print(f"✓ Original moved to: s3://{OUTPUT_BUCKET}/{archive_key}")
                      
                      results.append({
                          'input': key,
                          'output': output_key,
                          'count': len(labeled_feedbacks),
                          'status': 'success'
                      })
                      
                  except Exception as e:
                      print(f"✗ Error processing {key}: {str(e)}")
                      import traceback
                      traceback.print_exc()
                      results.append({
                          'input': key,
                          'status': 'error',
                          'error': str(e)
                      })
              
              return {
                  'statusCode': 200,
                  'body': json.dumps(results)
              }

  # Lambda Permission for S3 to invoke
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref FeedbackLabelingFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt FeedbackBucket.Arn
      SourceAccount: !Ref AWS::AccountId

  # Custom resource to add S3 notification after everything is created
  S3NotificationCustomResource:
    Type: Custom::S3BucketNotification
    Properties:
      ServiceToken: !GetAtt S3NotificationFunction.Arn
      BucketName: !Ref FeedbackBucket
      LambdaArn: !GetAtt FeedbackLabelingFunction.Arn
      NotificationId: FeedbackIngressNotification

  # Lambda to configure S3 notifications
  S3NotificationFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'sunray-feedback-nova-${Environment}-s3-config'
      Runtime: python3.11
      Handler: index.handler
      Role: !GetAtt S3NotificationFunctionRole.Arn
      Timeout: 60
      Code:
        ZipFile: |
          import json
          import boto3
          import cfnresponse
          
          s3 = boto3.client('s3')
          
          def handler(event, context):
              print(f"Event: {json.dumps(event)}")
              
              try:
                  bucket = event['ResourceProperties']['BucketName']
                  lambda_arn = event['ResourceProperties']['LambdaArn']
                  notification_id = event['ResourceProperties']['NotificationId']
                  
                  if event['RequestType'] in ['Create', 'Update']:
                      s3.put_bucket_notification_configuration(
                          Bucket=bucket,
                          NotificationConfiguration={
                              'LambdaFunctionConfigurations': [
                                  {
                                      'Id': notification_id,
                                      'LambdaFunctionArn': lambda_arn,
                                      'Events': ['s3:ObjectCreated:*'],
                                      'Filter': {
                                          'Key': {
                                              'FilterRules': [
                                                  {'Name': 'prefix', 'Value': 'ingress/'},
                                                  {'Name': 'suffix', 'Value': '.json'}
                                              ]
                                          }
                                      }
                                  }
                              ]
                          }
                      )
                      print(f"✓ Notification configured for bucket: {bucket}")
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
                      
                  elif event['RequestType'] == 'Delete':
                      try:
                          s3.put_bucket_notification_configuration(
                              Bucket=bucket,
                              NotificationConfiguration={}
                          )
                          print(f"✓ Notification removed from bucket: {bucket}")
                      except Exception as e:
                          print(f"Note: Could not remove notification: {e}")
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
                      
              except Exception as e:
                  print(f"✗ Error: {str(e)}")
                  cfnresponse.send(event, context, cfnresponse.FAILED, {'Error': str(e)})

  # Role for the S3 notification configuration Lambda
  S3NotificationFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3NotificationConfig
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutBucketNotification
                  - s3:GetBucketNotification
                Resource: !GetAtt FeedbackBucket.Arn

Outputs:
  StackName:
    Description: CloudFormation stack name
    Value: !Ref AWS::StackName
    
  Environment:
    Description: Deployment environment
    Value: !Ref Environment
    
  BucketName:
    Description: S3 Bucket for feedback files
    Value: !Ref FeedbackBucket
    Export:
      Name: !Sub 'sunray-feedback-nova-${Environment}-BucketName'
  
  IngressFolder:
    Description: Upload raw feedback JSON files here
    Value: !Sub 's3://${FeedbackBucket}/ingress/'
    
  EgressFolder:
    Description: Labeled feedback appears here
    Value: !Sub 's3://${FeedbackBucket}/egress/'
    
  ArchiveFolder:
    Description: Processed files are moved here
    Value: !Sub 's3://${FeedbackBucket}/archive/'
  
  LambdaFunctionName:
    Description: Lambda function processing the feedback
    Value: !Ref FeedbackLabelingFunction
    Export:
      Name: !Sub 'sunray-feedback-nova-${Environment}-LambdaFunction'
    
  NovaModelUsed:
    Description: Amazon Nova model being used
    Value: !Ref NovaModelId
    
  Region:
    Description: AWS Region
    Value: !Ref AWS::Region
    
  CloudWatchLogGroup:
    Description: View Lambda logs here
    Value: !Sub 'https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fsunray-feedback-nova-${Environment}-labeling-function'
  
  S3Console:
    Description: Open S3 bucket in console
    Value: !Sub 'https://s3.console.aws.amazon.com/s3/buckets/${FeedbackBucket}?region=${AWS::Region}'
    
  TestCommand:
    Description: CLI command to test with sample file
    Value: !Sub 'aws s3 cp sample-feedback.json s3://${FeedbackBucket}/ingress/ --region ${AWS::Region}'
    
  SetupInstructions:
    Description: Setup steps after deployment
    Value: !Sub |
      1. Create folders:
         aws s3api put-object --bucket ${FeedbackBucket} --key ingress/
         aws s3api put-object --bucket ${FeedbackBucket} --key egress/
         aws s3api put-object --bucket ${FeedbackBucket} --key archive/
      2. Test Nova model once in Bedrock playground
      3. Upload test file to ingress/ folder